### ISSUE TITLE
Running `configure` with key/user/endpoint and no-interaction arguments ends in endless loop

### ISSUE THREAD

**Issue by slde-rorschach** [sensiolabs/insight#55]
Hello.

I tried to script insight configuration and run the following command:
```bash
insight.phar configure --api-token=TOPSECRET --user-uuid=ALSOSECRET --api-endpoint=https://insight.sensiolabs.com --no-interaction
```
I expected, that the `~/.sensiolabs/insight.json` would be created.

Instead the error message `Your must answer this question.` is printed in an endless loop.

Seems, the arguments for user/key are not recognized by this command.

Best regards
 Lukas

**Comment by lyrixx** [comment]
Hello @slde-rorschach ; Thanks for this report. Are you able to open a PR in order to fix this issue? If not, let me know, and I will take care of it.
