### ISSUE TITLE
PHP 7.1 nullable return type and type hinting not supported

### ISSUE THREAD

**Issue by abienvenu** [sensiolabs/insight#59]
This syntax is valid in PHP 7.1 (not 7.0), but Insight will report it as a syntax error:
`public function getId(): ?int`
`public function setDescription(?string $description)`

I tried to put 7.1 in the "advanced configuration" of the Insight project, but it was not accepted:

> php_version only supports: 5 or 7

**Comment by lyrixx** [comment]
hello @abienvenu 

You are right. We are going to add the PHP 7.1 support very soon.

I will keep up updated.

**Comment by lyrixx** [comment]
Hello @abienvenu 

I totally forgot to keep you updated.

We deployed PHP 7.1 few month ago. Everything should be fine now.
