### ISSUE TITLE
SPDX licenses.

### ISSUE THREAD

**Issue by Maikuolan** [sensiolabs/insight#69]
Hi,

I recently started seeing a warning from Packagist (not seen previously) for a particular package that the license that I'd been using in my `composer.json` file (GPL-2.0+) was deprecated. So, checking the [SPDX License List](https://spdx.org/licenses/), the information there confirms what Packagist was telling me, so I update my `composer.json` file to use "GPL-2.0-or-later" instead. After committing, I have Packagist attempt to update the package information, and no more complaints there, but now the SensioLabs Insight analysis for that package is showing:

> License "GPL-2.0-or-later" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
> If the software is closed-source, you may use "proprietary" as license.

So, not sure what I'm doing wrong here, or what I should be doing instead, to keep everything happy (Packagist + SensioLabs Insight analysis).

Any suggestions?

(Other than switching away from GNU/GPL of course, which is not desirable at this time).

**Comment by stof** [comment]
the issue here is that Insight runs an outdated version of Composer (using the old SPDX list)

**Comment by tgalopin** [comment]
Hello,

Thanks for the feedback @Maikuolan, I'm going to fix that on Monday.

**Comment by Maikuolan** [comment]
You're welcome, and cheers for the fix. :-)

**Comment by tgalopin** [comment]
Hello @Maikuolan,

It is now fixed, thanks for the feedback!

**Comment by Maikuolan** [comment]
Awesome! Cheers. :-)
